{
'public:adhoc10GB:lineitemHash' : [('l_orderkey', 'LONG_TYPE'), ('l_linenumber', 'LONG_TYPE'), ('l_custkey', 'LONG_TYPE'), ('l_partkey', 'LONG_TYPE'), ('l_suppkey', 'LONG_TYPE'), ('l_orderdate', 'STRING_TYPE'), ('l_orderpriority', 'STRING_TYPE'), ('l_shippriority', 'LONG_TYPE'), ('l_quantity', 'FLOAT_TYPE'), ('l_extendedprice', 'FLOAT_TYPE'), ('l_ordtotalprice', 'FLOAT_TYPE'), ('l_discount', 'FLOAT_TYPE'), ('l_revenue', 'LONG_TYPE'), ('l_supplycost', 'LONG_TYPE'), ('l_tax', 'FLOAT_TYPE'), ('l_commitdate', 'LONG_TYPE'), ('l_shipmode', 'STRING_TYPE')],
'public:adhoc10GB:supplierReplicate' : [('s_suppkey', 'LONG_TYPE'), ('s_name', 'STRING_TYPE'), ('s_address', 'STRING_TYPE'), ('s_city', 'STRING_TYPE'), ('s_nation_prefix', 'STRING_TYPE'), ('s_nation', 'STRING_TYPE'), ('s_region', 'STRING_TYPE'), ('s_phone', 'STRING_TYPE')],
'public:adhoc10GB:customerReplicate' : [('c_custkey', 'LONG_TYPE'), ('c_name', 'STRING_TYPE'), ('c_address', 'STRING_TYPE'), ('c_city', 'STRING_TYPE'), ('c_nation_prefix', 'STRING_TYPE'), ('c_nation', 'STRING_TYPE'), ('c_region', 'STRING_TYPE'), ('c_phone', 'STRING_TYPE'), ('c_mktsegment', 'STRING_TYPE')],
'public:adhoc10GB:partReplicate' : [('p_partkey', 'LONG_TYPE'), ('p_name', 'STRING_TYPE'), ('p_mfgr', 'STRING_TYPE'), ('p_category', 'STRING_TYPE'), ('p_brand', 'STRING_TYPE'), ('p_color', 'STRING_TYPE'), ('p_type', 'STRING_TYPE'), ('p_size', 'LONG_TYPE'), ('p_container', 'STRING_TYPE')],
'public:adhoc10GB:dateReplicate' : [('d_datekey', 'LONG_TYPE'), ('d_date', 'STRING_TYPE'), ('d_dayofweek', 'STRING_TYPE'), ('d_month', 'STRING_TYPE'), ('d_year', 'LONG_TYPE'), ('d_yearmonthnum', 'LONG_TYPE'), ('d_yearmonth', 'STRING_TYPE'), ('d_daynuminweek', 'LONG_TYPE'), ('d_daynuminmonth', 'LONG_TYPE'), ('d_daynuminyear', 'LONG_TYPE'), ('d_monthnuminyear', 'LONG_TYPE'), ('d_weeknuminyear', 'LONG_TYPE'), ('d_sellingseason', 'STRING_TYPE'), ('d_lastdayinweekfl', 'STRING_TYPE'), ('d_lastdayinmonthfl', 'STRING_TYPE'), ('d_holidayfl', 'STRING_TYPE'), ('d_weekdayfl', 'STRING_TYPE')],
'public:syntheticBenchmark:fact' : [('fact_fk1', 'LONG_TYPE'), ('fact_fk2', 'LONG_TYPE'), ('fact_fk3', 'LONG_TYPE'), ('fact_fk4', 'LONG_TYPE'), ('fact_fk5', 'LONG_TYPE'), ('fact_att6', 'LONG_TYPE'), ('fact_att7', 'LONG_TYPE'), ('fact_att8', 'LONG_TYPE'), ('fact_att9', 'LONG_TYPE'), ('fact_att10', 'LONG_TYPE'), ('fact_att11', 'LONG_TYPE'), ('fact_att12', 'LONG_TYPE'), ('fact_att13', 'LONG_TYPE'), ('fact_att14', 'LONG_TYPE'), ('fact_att15', 'LONG_TYPE'), ('fact_att16', 'LONG_TYPE'), ('fact_att17', 'LONG_TYPE'), ('fact_att18', 'LONG_TYPE'), ('fact_att19', 'LONG_TYPE'), ('fact_att20', 'LONG_TYPE'), ('fact_pk', 'LONG_TYPE')],
'public:syntheticBenchmark:dimension1Replicate' : [('dim_pk1_1', 'LONG_TYPE'), ('dim_att2_1', 'STRING_TYPE'), ('dim_att3_1', 'STRING_TYPE'), ('dim_att4_1', 'STRING_TYPE')],
'public:syntheticBenchmark:dimension2Replicate' : [('dim_pk1_2', 'LONG_TYPE'), ('dim_att2_2', 'STRING_TYPE'), ('dim_att3_2', 'STRING_TYPE'), ('dim_att4_2', 'LONG_TYPE'), ('dim_att5_2', 'LONG_TYPE'), ('dim_att6_2', 'STRING_TYPE')],
'public:syntheticBenchmark:dimension3Replicate' : [('dim_pk1_3', 'LONG_TYPE'), ('dim_att2_3', 'STRING_TYPE'), ('dim_att3_3', 'STRING_TYPE'), ('dim_att4_3', 'STRING_TYPE'), ('dim_att5_3', 'LONG_TYPE'), ('dim_att6_3', 'LONG_TYPE'), ('dim_att7_3', 'LONG_TYPE'), ('dim_att8_3', 'STRING_TYPE')],
'public:syntheticBenchmark:dimension4Replicate' : [('dim_pk1_4', 'LONG_TYPE'), ('dim_att2_4', 'STRING_TYPE'), ('dim_att3_4', 'STRING_TYPE'), ('dim_att4_4', 'STRING_TYPE'), ('dim_att5_4', 'STRING_TYPE'), ('dim_att6_4', 'LONG_TYPE'), ('dim_att7_4', 'LONG_TYPE'), ('dim_att8_4', 'LONG_TYPE'), ('dim_att9_4', 'LONG_TYPE'), ('dim_att10_4', 'STRING_TYPE')],
'public:syntheticBenchmark:dimension5Replicate' : [('dim_pk1_5', 'LONG_TYPE'), ('dim_att2_5', 'STRING_TYPE'), ('dim_att3_5', 'STRING_TYPE'), ('dim_att4_5', 'STRING_TYPE'), ('dim_att5_5', 'STRING_TYPE'), ('dim_att6_5', 'STRING_TYPE'), ('dim_att7_5', 'LONG_TYPE'), ('dim_att8_5', 'LONG_TYPE'), ('dim_att9_5', 'LONG_TYPE'), ('dim_att10_5', 'LONG_TYPE'), ('dim_att11_5', 'LONG_TYPE'), ('dim_att12_5', 'STRING_TYPE')],
}
