language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt
  - python setup.py install
  - pip install coveralls
  - sudo ln -fs `which clang++` `which g++`
script: nosetests --with-coverage --cover-package=raco --logging-level=WARN
after_success:
  - coveralls
